export function guess (path, name) {
  var info = {path: path, name: name, car: null, track: null}
  var tracks = [
    ['Atlanta', 'Atlanta Motor Speedway'],
    ['AutoClub', 'Auto Club Speedway'],
    ['Interlagos', 'Autodrome Jose Carlos Pace'],
    ['Imola', 'Autodromo Enzo e Dino Ferrari'],
    ['Monza', 'Autodromo Nazionale Monza'],
    ['Barber', 'Barber Motorsports Park'],
    ['Brands', 'Brands Hatch'],
    ['Bristol', 'Bristol Motor Speedway'],
    ['Mosport', 'Canadian Tire Motorsports Park'],
    ['Centripetal', 'Centripetal Circuit'],
    ['Charlotte', 'Charlotte Motor Speedway'],
    ['Chicagoland', 'Chicagoland Speedway'],
    ['Spa', 'Circuit de Spa-Francorchamps'],
    ['LeMans', 'Circuit des 24 Heures du Mans'],
    ['Montreal', 'Circuit Gilles Villeneuve'],
    ['COTA', 'Circuit of the Americas'],
    ['Zolder', 'Circuit Zolder'],
    ['Concord', 'Concord Speedway'],
    ['Darlington', 'Darlington Raceway'],
    ['Daytona2007', 'Daytona circa 2007'],
    ['Daytona', 'Daytona International Speedway'],
    ['Detroit', 'Detroit Grand Prix at Belle Isle'],
    ['Belle', 'Detroit Grand Prix at Belle Isle'],
    ['Donington', 'Donington Park Racing Circuit'],
    ['Dover', 'Dover International Speedway'],
    ['Eldora', 'Eldora Speedway'],
    ['FiveFlags', 'Five Flags Speedway'],
    ['Gateway', 'Gateway Motorsports Park'],
    ['Miami', 'Homestead Miami Speedway'],
    ['Indy', 'Indianapolis Motor Speedway'],
    ['IOWA', 'Iowa Speedway'],
    ['Irwindale', 'Irwindale Speedway'],
    ['ISM', 'ISM Raceway'],
    ['Kansas', 'Kansas Speedway'],
    ['Kentucky', 'Kentucky Speedway'],
    ['Knoxville', 'Knoxville Raceway'],
    ['Langley', 'Langley Speedway'],
    ['Lanier', 'Lanier National Speedway'],
    ['Vegas', 'Las Vegas Motor Speedway'],
    ['Limaland', 'Limaland Motorsports Park'],
    ['LimeRock', 'Lime Rock Park'],
    ['LongBeach', 'Long Beach Street Circuit'],
    ['LucasOil', 'Lucas Oil Raceway'],
    ['Martinsville', 'Martinsville Speedway'],
    ['Laguna', 'Mazda Raceway Laguna Seca'],
    ['Michigan', 'Michigan International Speedway'],
    ['MidOhio', 'Mid-Ohio Sports Car Course'],
    ['Bathurst', 'Mount Panorama Circuit'],
    ['Myrtle', 'Myrtle Beach Speedway'],
    ['Hampshire', 'New Hampshire Motor Speedway'],
    ['Jersey', 'New Jersey Motorsports Park'],
    ['Smyrna', 'New Smyrna Speedway'],
    ['Nordschleife', 'Nurburgring Combined'],
    ['Nurb', 'Nurburgring Grand Prix'],
    ['Nordschleife', 'Nurburgring Nordschleife'],
    ['Okayama', 'Okayama International Circuit'],
    ['Oran', 'Oran Park Raceway'],
    ['Oulton', 'Oulton Park Circuit'],
    ['Oxford', 'Oxford Plains Speedway'],
    ['Philip', 'Phillip Island'],
    ['Phoenix', 'Phoenix circa 2008'],
    ['Pocono2011', 'Pocono Raceway - 2011'],
    ['Pocono', 'Pocono Raceway'],
    ['Richmond', 'Richmond International Raceway'],
    ['RoadAmerica', 'Road America'],
    ['RAmer', 'Road America'],
    ['RoadAtlanta', 'Road Atlanta'],
    ['PetitLeMans', 'Road Atlanta'],
    ['RAtl', 'Road Atlanta'],
    ['Rockingham', 'Rockingham Speedway'],
    ['Sebring', 'Sebring International Raceway'],
    ['Silverstone', 'Silverstone Circuit'],
    ['Snetterton', 'Snetterton Circuit'],
    ['Sonoma', 'Sonoma Raceway'],
    ['Bostn', 'South Boston Speedway'],
    ['Southern', 'Southern National Motorsports Park'],
    ['Stafford', 'Stafford Motor Speedway'],
    ['Summit', 'Summit Point Raceway'],
    ['Suzuka', 'Suzuka International Racing Course'],
    ['Talladega', 'Talladega Superspeedway'],
    ['Texas', 'Texas Motor Speedway'],
    ['Bullring', 'The Bullring'],
    ['Charlotte', 'The Dirt Track at Charlotte'],
    ['Milwaukee', 'The Milwaukee Mile'],
    ['Thompson', 'Thompson International Speedway'],
    ['Motegi', 'Twin Ring Motegi'],
    ['USA', 'USA International Speedway'],
    ['VIR', 'Virginia International Raceway'],
    ['Virginia', 'Virginia International Raceway'],
    ['Volusia', 'Volusia Speedway Park'],
    ['Glen', 'Watkins Glen International'],
    ['Watkins', 'Watkins Glen International'],
    ['Williams', 'Williams Grove Speedway'],
    ['Zandvoort', 'Zandvoort']
  ]
  var cars = [
    ['aston', 'Aston Martin DBR9 GT1', 'astonmartin dbr9'],
    ['gto', 'Audi 90 GTO', 'audi90gto'],
    ['r18', 'Audi R18', 'audir18'],
    ['r8', 'Audi R8 LMS GT3', 'audir8gt3'],
    ['z4', 'BMW Z4 GT3', 'bmwz4gt3'],
    ['caddy', 'Cadillac CTS-VR'],
    ['cadillac', 'Cadillac CTS-VR'],
    ['c6r', 'Chevrolet Corvette C6R', 'c6r'],
    ['c7', 'Chevrolet Corvette C7 Daytona Prototype', 'c7vettedp'],
    ['dp', 'Chevrolet Corvette C7 Daytona Prototype', 'c7vettedp'],
    ['impala', 'Chevrolet Impala'],
    ['null', 'Chevrolet Impala Old Class B'],
    ['null', 'Chevrolet Impala SS 2009'],
    ['null', 'Chevrolet Monte Carlo SS'],
    ['null', 'Chevrolet Silverado - Circa 2013'],
    ['dallara', 'Dallara DW12', 'dallara'],
    ['indycar', 'Dallara Indycar'],
    ['ir18', 'Dallara IR18', 'dallarair18'],
    ['null', 'Dirt Late Model - Limited'],
    ['null', 'Dirt Late Model - Pro'],
    ['null', 'Dirt Late Model - Super'],
    ['null', 'Dirt Legends Ford 34 Coupe'],
    ['null', 'Dirt Midget'],
    ['null', 'Dirt Sprint Car - 305'],
    ['null', 'Dirt Sprint Car - 360'],
    ['null', 'Dirt Sprint Car - 360 Non-Winged'],
    ['null', 'Dirt Sprint Car - 410'],
    ['null', 'Dirt Sprint Car - 410 Non-Winged'],
    ['null', 'Dirt Street Stock'],
    ['null', 'Dirt UMP Modified'],
    ['488gt3', 'Ferrari 488 GT3', 'ferrari488gt3'],
    ['488gte', 'Ferrari 488 GTE', 'ferrari488gte'],
    ['488e', 'Ferrari 488 GTE', 'ferrari488gte'],
    ['null', 'Ford Falcon FG V8'],
    ['null', 'Ford Falcon FG01 V8 - Circa 2012'],
    ['null', 'Ford Fiesta RS WRC'],
    ['fordgte', 'Ford GT - 2017', 'fordgt2017'],
    ['fordgt3', 'Ford GT GT3', 'fordgt3'],
    ['ford', 'Ford GT', 'fordgt'],
    ['null', 'Ford Mustang FR500S'],
    ['fr20', 'Formula Renault 2.0', 'formularenault20'],
    ['fr2.0', 'Formula Renault 2.0', 'formularenault20'],
    ['null', 'Global Mazda MX5 Cup'],
    ['null', 'Holden Commodore VF V8'],
    ['hpd', 'HPD ARX-01c', 'hpdarx01c'],
    ['null', 'Kia Optima GX'],
    ['null', 'Legends Ford 34 Coupe '],
    ['null', 'Legends Ford 34 Coupe - Rookie '],
    ['lotus49', 'Lotus 49', 'lotus49'],
    ['lotus79', 'Lotus 79', 'lotus79'],
    ['null', 'Mazda MX-5 Cup'],
    ['null', 'Mazda MX-5 Roadster'],
    ['macca', 'McLaren MP4-12C', 'mclarenmp4'],
    ['mp4', 'McLaren MP4-12C', 'mclarenmp4'],
    ['mp430', 'McLaren MP4-30', 'mclarenmp430'],
    ['f1', 'McLaren MP4-30', 'mclarenmp430'],
    ['amg', 'Mercedes AMG GT3', 'mercedesamggt3'],
    ['merc', 'Mercedes AMG GT3', 'mercedesamggt3'],
    ['silverado', 'NASCAR Camping World Chevrolet Silverado', 'trucks silverado'],
    ['null', 'NASCAR Camping World Toyota Tundra'],
    ['null', 'NASCAR Sprint Cup Chevrolet SS'],
    ['null', 'NASCAR Sprint Cup Ford Fusion'],
    ['null', 'NASCAR Sprint Cup Toyota Camry'],
    ['null', 'NASCAR XFINITY Chevrolet Camaro'],
    ['null', 'NASCAR XFINITY Ford Mustang'],
    ['null', 'NASCAR XFINITY Toyota Camry'],
    ['nissan', 'Nissan GTP ZX-T', 'nissangtpzxt'],
    ['solstice', 'Pontiac Solstice', 'solstice'],
    ['slowstice', 'Pontiac Solstice', 'solstice'],
    ['Cup', 'Porsche 911 GT3 Cup (991)', 'porsche911cup'],
    ['RSR', 'Porsche 911 RSR', 'porsche991rsr'],
    ['919', 'Porsche 919', 'porsche919'],
    ['null', 'Pro Mazda'],
    ['null', 'Radical SR8'],
    ['null', 'Riley MkXX Daytona Prototype'],
    ['ruf', 'Ruf RT 12R AWD', 'ruf12r awd'],
    ['ruf', 'Ruf RT 12R C-Spec', 'ruf12r cspec'],
    ['ruf', 'Ruf RT 12R RWD', 'ruf12r rwd'],
    ['ruf', 'Ruf RT 12R Track', 'ruf12r track'],
    ['specracer', 'SCCA Spec Racer Ford', 'specracer'],
    ['null', 'Silver Crown'],
    ['null', 'SK Modified'],
    ['null', 'SK Tour Modified'],
    ['skippy', 'Skip Barber Formula 2000', 'rt2000'],
    ['null', 'Sprint Car'],
    ['null', 'Street Stock'],
    ['null', 'Subaru WRX STI'],
    ['null', 'Super Late Model'],
    ['vw', 'VW Beetle GRC', 'vwbeetlegrc'],
    ['null', 'VW Jetta TDI Cup'],
    ['williams', 'Williams-Toyota FW31', 'williamsfw31']
  ]
  tracks.forEach(e => {
    if (name.toLowerCase().includes(e[0].toLowerCase())) {
      info.track = e
    }
  })
  cars.forEach(e => {
    if (name.toLowerCase().includes(e[0].toLowerCase())) {
      info.car = e
    }
  })
  return info
}
export default guess
